workflows:
  custom_build:
    name: Custom Build Workflow
    environment:
      flutter: stable # Specify the Flutter version if needed
      vars:
        CUSTOM_ENV_VAR: "CustomValue"
    scripts:
      - name: Run build_pub_dev.sh
        script: |
          echo "Running build_pub_dev.sh..."
          chmod +x build_pub_dev.sh
          ./build_pub_dev.sh
    publishing:
      email:
        recipients:
          - your_email@example.com
