workflows:
  custom_build:
    name: Custom Build Workflow
    environment:
      flutter: stable # Specify the Flutter version if needed
      vars:
        CUSTOM_ENV_VAR: "CustomValue"
    scripts:
      - name: Run build.sh
        script: |
          echo "Running build.sh..."
          chmod +x build.sh
          ./build.sh
      - name: Install GPG
        script: |
          echo "Installing GPG..."
          if [ "$(uname)" = "Darwin" ]; then
            brew install gnupg || echo "GPG already installed."
          else
            sudo apt-get update && sudo apt-get install -y gnupg
          fi
          gpg --version
      - name: Run assemble.py
        script: |
          echo "Running assemble.py..."
          pip install requests
          python3 assemble.py
      - name: Verify amwal_sdk.zip
        script: |
          echo "Checking if amwal_sdk.zip exists..."
          if [ -f ./amwal_sdk.zip ]; then
            echo "amwal_sdk.zip found!"
          else
            echo "amwal_sdk.zip not found!" && exit 1
          fi
      - name: Create workspace directory
        script: |
          echo "Creating /workspace directory..."
          mkdir -p /workspace
      - name: Move amwal_sdk.zip to workspace
        script: |
          echo "Moving amwal_sdk.zip to /workspace for artifact storage..."
          mv ./amwal_sdk.zip /workspace/
      - name: Run build_pub_dev.sh
        script: |
          echo "Running build_pub_dev.sh..."
          chmod +x build_pub_dev.sh
          ./build_pub_dev.sh
    artifacts:
      - /workspace/amwal_sdk.zip # Save amwal_sdk.zip as an artifact
    publishing:
      email:
        recipients:
          - your_email@example.com
