workflows:
  custom_build:
    name: Custom Build Workflow
    environment:
      flutter: stable # Specify the Flutter version if needed
      vars:
        CUSTOM_ENV_VAR: "CustomValue"
    scripts:
      - name: Run build.sh
        script: |
          echo "Running build.sh..."
          chmod +x build.sh
          ./build.sh
      - name: Install GPG
        script: |
          echo "Installing GPG..."
          if [ "$(uname)" = "Darwin" ]; then
            brew install gnupg || echo "GPG already installed."
          else
            sudo apt-get update && sudo apt-get install -y gnupg
          fi
          gpg --version
      - name: Run assemble.py
        script: |
          echo "Running assemble.py..."
          python3 assemble.py
    artifacts:
      - /workspace/*.zip # Save all zip files in the root directory as artifacts
    publishing:
      email:
        recipients:
          - your_email@example.com
