workflows:
  my-workflow:
    environment:
      flutter: stable
    scripts:
      - name: Build Android AAR
        script: flutter build aar
    artifacts:
      - app/build/outputs/**/**/*.aar



