workflows:
  my-workflow:
    environment:
      flutter: stable
    scripts:
      - name: Build Android AAR
        script: flutter build aar
    artifacts:
      - build/host/outputs/repo/**/**/**/*.pom
      - build/host/outputs/repo/**/**/*.aar





