# Uncomment the next line to define a global platform for your project
#platform :ios, '12.0' # Recommended minimum iOS version

flutter_application_path = '../amwal_sdk_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'AnwalPaySDKNativeiOSExample' do
  use_frameworks! # Required for Flutter modules

   install_all_flutter_pods(flutter_application_path) # Ensure this is inside the target

end



post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
