name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Remove build scripts
        run: |
          if [ -f "build.sh" ]; then
            echo "Removing build.sh..."
            rm build.sh
          fi
          
          if [ -f "assemble.py" ]; then
            echo "Removing assemble.py..."
            rm assemble.py
          fi
          
          echo "Build scripts removed successfully!"
  
  publish:
    needs: cleanup
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      # working-directory: path/to/package/within/repository
      force: true